controller_list:
  - name: fake_back_left_controller
    joints:
      - back_left_hip_swing_joint
      - back_left_hip_lateral_joint
      - back_left_knee_joint
      - back_left_ankle_joint
  - name: fake_back_right_controller
    joints:
      - back_right_hip_swing_joint
      - back_right_hip_lateral_joint
      - back_right_knee_joint
      - back_right_ankle_joint
  - name: fake_front_left_controller
    joints:
      - front_left_hip_swing_joint
      - front_left_hip_lateral_joint
      - front_left_knee_joint
      - front_left_ankle_joint
  - name: fake_front_right_controller
    joints:
      - front_right_hip_swing_joint
      - front_right_hip_lateral_joint
      - front_right_knee_joint
      - front_right_ankle_joint
  - name: fake_front_legs_controller
    joints:
      - front_left_hip_swing_joint
      - front_left_hip_lateral_joint
      - front_left_knee_joint
      - front_left_ankle_joint
      - front_right_hip_swing_joint
      - front_right_hip_lateral_joint
      - front_right_knee_joint
      - front_right_ankle_joint
  - name: fake_back_legs_controller
    joints:
      - back_left_hip_swing_joint
      - back_left_hip_lateral_joint
      - back_left_knee_joint
      - back_left_ankle_joint
      - back_right_hip_swing_joint
      - back_right_hip_lateral_joint
      - back_right_knee_joint
      - back_right_ankle_joint
  - name: fake_torso_controller
    joints:
      []
  - name: fake_robot_controller
    joints:
      - back_left_hip_swing_joint
      - back_left_hip_lateral_joint
      - back_left_knee_joint
      - back_left_ankle_joint
      - back_right_hip_swing_joint
      - back_right_hip_lateral_joint
      - back_right_knee_joint
      - back_right_ankle_joint
      - front_left_hip_swing_joint
      - front_left_hip_lateral_joint
      - front_left_knee_joint
      - front_left_ankle_joint
      - front_right_hip_swing_joint
      - front_right_hip_lateral_joint
      - front_right_knee_joint
      - front_right_ankle_joint