string command
uint8 duration

string START_LISTENING	=	start listening
string STOP_LISTENING	=	stop listening
string GO_TO_SLEEP		=	go to sleep
string WAKE_UP			=	wake up
string MOVE_FORWARD		=	move forward
string MOVE_BACKWORD	=	move backward
string MOVE_LEFT		=	move left
string MOVE_RIGHT		=	move right
string TURN_LEFT		=	turn left
string TURN_RIGHT		=	turn right
string MOVE_FASTER		=	move faster
string SPEED_UP			=	speed up
string MOVE_SLOWER		=	move slower
string SLOW_DOWN		=	slow down
string QUARTER_SPEED	=	quarter speed
string HALF_SPEED		=	half speed
string FULL_SPEED		=	full speed
string CANCEL			=	cancel
string STOP=stop
string ABORT			=	abort
string PANIC			=	panic
string HELP				=	help
string TURN_OFF			=	turn off
string SHUT_DOWN		=	shut down
